### ISSUE TITLE
The chain of replies on Twitter is displayed in the wrong order

### ISSUE THREAD

**Issue by DmB-Ekb** [crimera/piko#565]
The attached pictures show an example of how the previous tweets, for example, for [this tweet](https://x.com/cap_zvezdoleta/status/1913090403735044200) are displayed in the browser (correct order) and in the application with the patch (wrong order).  In the app without the patch, the order is correct. 
The situation is observed in several recent versions of the patch, including the most recent one (updated today).

![Image](https://github.com/user-attachments/assets/6e501d90-167f-41e8-8fd0-9a1e806f8983)

![Image](https://github.com/user-attachments/assets/d02dd790-999d-4e8f-b935-315641211548)

**Comment by DmB-Ekb** [comment]
I'll explain it schematically to avoid the language barrier for pictures.If we assign the conditional number 0 to the starting tweet, then the fifth replay in the chain, instead of the logical scheme:
0
1
2
3
4
5

 is displayed according to the following scheme:
4
3
2
1
0
5

**Comment by DmB-Ekb** [comment]
Hi @crimera ,

Thank you for your work on the patched version of the X app for Android. I've already described the sorting issue I'm facing in the app, but after some investigation, I believe I've pinpointed the root cause, and I'd like to kindly request a potential improvement in your patch, if feasible.

It appears that the sorting glitch in threaded conversations is tied to X's default reply sorting setting. In the official Android app, the default sorting is set to "Most Liked," which prioritizes replies based on their likes rather than their chronological order. This makes conversations nearly unreadable, as the thread's logical flow is disrupted, with popular replies jumping to the top regardless of their place in the discussion. In contrast, the browser version defaults to "Most Recent," which preserves the chronological order and makes threads coherent and easy to follow.

This default "Most Liked" setting in the Android app feels like a design flaw for several reasons:

- Disrupted User Experience: For users who rely on X for discussions, the "Most Liked" default breaks the natural flow of conversations, forcing manual sorting to "Most Recent" for every single post, which is tedious and frustrating.

- Inconsistency Across Platforms: The difference in default settings between the Android app ("Most Liked") and the browser ("Most Recent") creates a jarring experience for users who switch between platforms, as the same threads look completely different.

- Lack of Customization: X currently doesn't allow users to save their preferred sorting option (e.g., "Most Recent") as the default, meaning the inconvenient "Most Liked" setting persists across sessions, forcing users to repeatedly adjust it manually.

Given your expertise in patching the X app, I was wondering if it would be possible to modify the default reply sorting behavior in your patched version to set "Most Recent" as the default instead of "Most Liked." This change would significantly improve the usability of threaded conversations, aligning the Android app's behavior with the browser version and addressing a common user pain point. If this is within the scope of your patch, I believe it would be a highly appreciated feature for many users who value chronological clarity in discussions.

Please let me know if this is something you could consider or if there are any technical limitations to implementing it. I'm happy to provide more details or feedback if needed. Thanks again for your amazing work!

**Comment by DmB-Ekb** [comment]
It seems that the sorting error has somehow resolved itself. This is observed with the same application version and the same sorting option ("Most Liked") setting that previously caused the issue.

Given this unexpected resolution, I cautiously assume that the problem was likely with Twitter itself, and they have somehow addressed it on their end.

**Comment by DmB-Ekb** [comment]
@user334 I have both of these threads displaying correctly.
However, I just updated to the latest version of the application (11.3.5-release.0), but yesterday I had the problematic tracks displayed properly in the 10.89.1-release.0 version as well.
Try updating the version too. If that doesn't help, the problem will become even more mysterious )

![Image](https://github.com/user-attachments/assets/09bbb736-ab8d-445c-a386-587745c199db)
![Image](https://github.com/user-attachments/assets/66e5e4a8-1f7b-4290-8465-71c9e0b85d74)

**Comment by DmB-Ekb** [comment]
@user334 Please let me know whether you still have the error after updating the app (if you do, I'll reopen the issue)

**Comment by eepykate** [comment]
Personally still getting this when using the most liked reply sorting (seems like most relevant helps, thank you so much dmb!!), but it comes and goes without any clear reason.  most likely just one of elmos api flaws then :)

**Comment by coolerrat** [comment]
Still getting this

**Comment by grishka** [comment]
>  default “Most Recent” (or "Most Relevant") sorting mode for replies to the patch

The option is there, at least in the latest build, under Piko settings -> Customization -> Default reply sorting filter. Selecting it does make tweets appear in the right order.

<img width="1280" height="2856" alt="Image" src="https://github.com/user-attachments/assets/a8c0ef13-4708-42cb-a801-719bdf29e3e9" />

**Comment by DmB-Ekb** [comment]
> The option is there

Yes, thank you very much, I found this option in the settings, and it works exactly as it should!
I had been trying unsuccessfully to find it before. If it was available in older versions, I apologize for not noticing it )

**Comment by DmB-Ekb** [comment]
Сlosing this topic again, as a solution has been found. Many thanks to @grishka and @crimera )

**Comment by DmB-Ekb** [comment]
Although the basic problem with replies sorting has been solved, it turns out that the “Most Liked” sorting mode is important to some people )
OK, I'm reopening the issue in case it's possible to fix the replies sorting in this mode as well.

**Comment by omeriakyuz** [comment]
The error still persists. Choosing the most recent option works, but it's not the usual sorting. Twitter's default sort is most liked.
